export const CORSProxyList = {
    corsanywhere: 'https://cors-anywhere.herokuapp.com/',
    crossorigin: 'http://crossorigin.me/',
    corsproxy: 'http://cors-proxy.htmldriven.com/?url=',
    whateverorigin: 'http://www.whateverorigin.org/get?url=',
    corsio: 'https://cors.io/?',
    drysierra94326: 'http://dry-sierra-94326.herokuapp.com/',
    thingproxy: 'https://thingproxy.freeboard.io/fetch/',
    corsnowsh: 'https://cors.now.sh/',
    freecorsproxy: 'https://free-cors-proxy.herokuapp.com',
    corsproxyourbuildo: 'https://corsproxy.our.buildo.io',
    corsifyme: 'http://www.corsify.me/',
    gobetween: 'http://gobetween.oklabs.org/pipe/',
    corshyooru: 'http://cors.hyoo.ru/',
    cors4js: 'https://cors4js.appspot.com/?url=',
    fuckcors: 'http://fuck-cors.com/?url=',
    proxysauce: 'https://proxy-sauce.glitch.me/',
};